# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Mar 14 10:05:38 2023
#

import wx
from ExportPrincipalVerif import ExportPrincipalVerif
from create_event import create_event
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Exporter(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Exporter.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Exporter")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        sizer_3.Add((0, 0), 0, 0, 0)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, "Identifiant de l'agenda :")
        sizer_4.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.txt_id_google = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        sizer_4.Add(self.txt_id_google, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        sizer_3.Add((0, 0), 0, 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        self.button_APPLY = wx.Button(self, wx.ID_APPLY, "")
        sizer_2.AddButton(self.button_APPLY)

        self.button_primary = wx.Button(self, wx.ID_ANY, "Exporter sur l'agenda principal")
        sizer_2.Add(self.button_primary, 0, 0, 0)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.OnExportConfirmed, self.button_APPLY)
        self.Bind(wx.EVT_BUTTON, self.OnExportPrimary, self.button_primary)
        # end wxGlade

    def OnExportConfirmed(self, event):  # wxGlade: Exporter.<event_handler>
        print("Création d'event sur agenda custom")
        id_google = (self.txt_id_google.GetValue())
        create_event(id_google)

    def OnExportPrimary(self, event):  # wxGlade: Exporter.<event_handler>
        print('ouverture de la vérif')
        addDialog = ExportPrincipalVerif(self)
        result = addDialog.ShowModal()
        if(result == wx.ID_OK):
            self.lblReturn.SetLabelText(addDialog.txtEvt.GetValue())

# end of class Exporter
