# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Mon Mar 13 10:01:52 2023
#

import wx
# begin wxGlade: dependencies
import wx.adv
import Ajout
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyCalendar(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyCalendar.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((431, 313))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.window_1 = wx.SplitterWindow(self.panel_1, wx.ID_ANY)
        self.window_1.SetMinimumPaneSize(20)
        sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)

        self.window_1_pane_1 = wx.Panel(self.window_1, wx.ID_ANY)

        grid_sizer_1 = wx.GridSizer(4, 2, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.lblReturn = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "Return")
        grid_sizer_1.Add(self.lblReturn, 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.window_1_pane_2 = wx.Panel(self.window_1, wx.ID_ANY)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        self.calendar = wx.adv.GenericCalendarCtrl(self.window_1_pane_2, wx.ID_ANY)
        sizer_2.Add(self.calendar, 0, 0, 0)

        sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        self.btnAdd = wx.Button(self.window_1_pane_2, wx.ID_ANY, "Ajout ...")
        sizer_3.Add(self.btnAdd, 0, wx.EXPAND, 0)

        self.button_2 = wx.Button(self.window_1_pane_2, wx.ID_ANY, "Exporter")
        sizer_3.Add(self.button_2, 0, wx.EXPAND, 0)

        self.window_1_pane_2.SetSizer(sizer_2)

        self.window_1_pane_1.SetSizer(grid_sizer_1)

        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.OnAdd, self.btnAdd)
        # end wxGlade

    def OnAdd(self, event):  # wxGlade: MyCalendar.<event_handler>
        secondWindow = Ajout()
        secondWindow.Show()

# end of class MyCalendar
